<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_jikpayung-existing</name>
   <tag></tag>
   <elementGuidId>bca71ec1-0984-4b22-b232-32c0b16f2f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ee43183-9cf5-4329-864d-e702b3871896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>48f37b5a-0a97-4b63-93f9-9973bb0b1b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5f5c9c8b-bc49-4be1-a80b-059427d03b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jikpayung-existing</value>
      <webElementGuid>795a1e28-52cb-4eb3-afef-c5ba6e25dbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1e0ad248-b739-4dd7-923c-221f2b7cca5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3b9a2e89-92d4-4c5d-878f-395920b9bd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no&quot;)</value>
      <webElementGuid>f60f992a-9414-42ba-931b-9301b8b21686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no']</value>
      <webElementGuid>49ef405c-c205-422d-b11b-43bde267e298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/form/fieldset/div/div[2]/input</value>
      <webElementGuid>2e616154-d296-4d81-8b8e-d8dd1a08dd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>fe60e5ed-babf-47d5-985d-ea08e34b24e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no' and @type = 'radio' and @name = 'jikpayung-existing']</value>
      <webElementGuid>a93abdd1-81be-4d57-80e7-46a0560a99d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
