<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__period</name>
   <tag></tag>
   <elementGuidId>855e14f6-0a57-4890-a735-4615360f8a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#period</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='period']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dec55581-35f0-4856-8cc0-150e066c0dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>period</value>
      <webElementGuid>67a091ea-2c3c-40e6-bb1b-e0a4f5c1b33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Partnership period</value>
      <webElementGuid>c2e4959a-cd21-4efa-a996-505bbdd6bff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>period</value>
      <webElementGuid>5897e2d6-5864-4b86-9e3d-ac78de04cb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4457b65d-7e4b-4a1b-85ae-a15bd308076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-dirty av-valid form-control</value>
      <webElementGuid>a639fb53-194e-4b30-a490-2e9dce11f93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;period&quot;)</value>
      <webElementGuid>4b89ea8d-d03e-4359-a3d4-1512eb0398ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='period']</value>
      <webElementGuid>c5cbda07-df77-49ba-aa19-61cf23e68507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/form/div[5]/input</value>
      <webElementGuid>e49a1424-331d-4601-8d6f-aeeac39f1fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>a598e61a-bbb9-4a09-9110-9bc52f58e52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'period' and @placeholder = 'Partnership period' and @id = 'period' and @type = 'number']</value>
      <webElementGuid>871c81ad-c2c2-433e-a6a4-376a1824f4c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
