<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve</name>
   <tag></tag>
   <elementGuidId>a91d84a5-37c9-459e-a7b6-2463e2a853f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48d6ee02-2f6f-435e-b5d5-3fbd1214c572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>206bbd74-2d4e-4320-9ff2-77baeb77ff4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>addclassname</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>b5609998-7d57-469f-9ad8-af4793c0fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>solid</value>
      <webElementGuid>d5605d90-2ef1-4226-87a1-ea8ba44009fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sized</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>1ae161a1-2f48-461a-8134-4ffe4ae0b917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-tpn mr-1</value>
      <webElementGuid>d4bbd13f-6f12-485b-847c-482cf223fe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>0581386f-228b-422b-8a60-73adeac9540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout theme-primary menu-collapsed navbar-sticky&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;justify-content-between row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;d-flex justify-content-end row&quot;]/button[@class=&quot;button-tpn mr-1&quot;]</value>
      <webElementGuid>33059c6c-2835-45c8-9c02-0c40867b3371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='success']</value>
      <webElementGuid>d2056dba-f3a9-4cc6-a3f5-2d78b1ce2146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div/div/div[2]/div/button[3]</value>
      <webElementGuid>91f5cf22-43a1-4671-bc81-074a1ddae2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/following::button[1]</value>
      <webElementGuid>e1fc6606-b2ec-487f-9cb0-4b65e093d9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::button[2]</value>
      <webElementGuid>e461e143-dfd2-40f2-ae21-0be12a08be48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Info'])[1]/preceding::button[1]</value>
      <webElementGuid>4db2720d-b4a3-40ee-94ba-28d121a74565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::button[1]</value>
      <webElementGuid>3d272bcf-5dbe-4504-a447-cc91de4b3429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve']/parent::*</value>
      <webElementGuid>d9d051d4-91ba-4e08-8a3a-4528c59fa77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>3cdd1745-9fec-40ae-a650-8f0abaec0141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'success' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>d039f658-1487-4194-9228-50a6b5001876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
