<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View Partnership</name>
   <tag></tag>
   <elementGuidId>ce34c15c-35f4-4765-951c-6fcfb65eb7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-tpn.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='primary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4db4b64a-4d36-404d-bc4a-ce205b96dfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>addclassname</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>b95c3969-9406-45a3-8cea-340297fad3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>bcabdc39-4dea-4ff3-ada3-aa0d220da317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>solid</value>
      <webElementGuid>e5c53ecb-fcca-4b6d-8586-a0ff2eb1eac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sized</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>7fc25599-8bed-4f8f-a61b-dc88fee14ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-tpn mr-1</value>
      <webElementGuid>ecc66783-bae6-43f3-b631-19fc702629ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Partnership</value>
      <webElementGuid>5d978ef4-be74-497c-9bff-0cdfd0ffa21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout theme-primary navbar-sticky&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;justify-content-between row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;d-flex justify-content-end row&quot;]/button[@class=&quot;button-tpn mr-1&quot;]</value>
      <webElementGuid>49f6cbfb-cea0-4d4f-a5f7-a6853c335ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='primary']</value>
      <webElementGuid>6178debe-19ec-40e6-8b7f-524a8e0e1188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div/div/div[2]/div/button</value>
      <webElementGuid>f2e25349-c89c-417b-bb2a-b17c13d6193a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Partnership PKS Fajar #1 26-01-2023'])[1]/following::button[1]</value>
      <webElementGuid>90e72396-278c-4c2c-93cb-478bbe2f6114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partnership Initiation Detail'])[1]/following::button[1]</value>
      <webElementGuid>49518161-1b78-45d3-b82b-98bcefa42e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/preceding::button[1]</value>
      <webElementGuid>1f18cf20-712a-4cbb-9247-0a220845ac8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Info'])[1]/preceding::button[1]</value>
      <webElementGuid>fe2fc0cd-af68-40ec-9339-04d7d31563f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Partnership']/parent::*</value>
      <webElementGuid>f5ff29c2-7065-4ecd-8694-1ad2ddf17299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>eba0c633-e020-4f5a-88c2-742434f2977f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'primary' and (text() = 'View Partnership' or . = 'View Partnership')]</value>
      <webElementGuid>9900ac65-fe33-4c12-a8d1-9f99b86f4a60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
