<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Partnership Model</name>
   <tag></tag>
   <elementGuidId>e5602f3c-5876-4f0f-bfc8-03a233a057d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;partnership-model-internal&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='partnership-model-internal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95c2e289-cf4f-4370-84b5-b6b255add167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partnership-model-internal</value>
      <webElementGuid>ad9567ed-9bd2-432e-b0b0-4fadfb39fc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control dropdown-select form-control</value>
      <webElementGuid>62cba86f-e83b-4c8b-8c98-f6d0d906b30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Partnership ModelAmandemen IncubationAmandemen Incubation AccelarationAmandemen Memorandum of UnderstandingAmandemen Partnership Agreement - BusinessAmandemen Partnership Agreement - ResearchIncubationIncubation AccelarationKontrak BerlanggananMemorandum of UnderstandingNon-Disclosure AgreementPartnership Agreement - BusinessTermination</value>
      <webElementGuid>97c949cc-35bd-4185-90f4-9f1fffe13c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout theme-primary menu-collapsed navbar-sticky&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-sm-12 col-md-5&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control dropdown-select form-control&quot;]</value>
      <webElementGuid>a9435010-b19b-440e-bb45-b99521fa7e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='partnership-model-internal']</value>
      <webElementGuid>4493d9d7-4bfa-4e64-a785-9b96f2846362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/div[9]/div/div/select</value>
      <webElementGuid>eb368d6c-a774-4bc4-853d-76d46a37d044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>f1981993-758c-4693-90a7-cb17a8280d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>255dd9a5-5495-4a50-9e91-c1f6a10de5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4bfbeea9-99e3-401b-8428-1326b4bea119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'partnership-model-internal' and (text() = 'Select Partnership ModelAmandemen IncubationAmandemen Incubation AccelarationAmandemen Memorandum of UnderstandingAmandemen Partnership Agreement - BusinessAmandemen Partnership Agreement - ResearchIncubationIncubation AccelarationKontrak BerlanggananMemorandum of UnderstandingNon-Disclosure AgreementPartnership Agreement - BusinessTermination' or . = 'Select Partnership ModelAmandemen IncubationAmandemen Incubation AccelarationAmandemen Memorandum of UnderstandingAmandemen Partnership Agreement - BusinessAmandemen Partnership Agreement - ResearchIncubationIncubation AccelarationKontrak BerlanggananMemorandum of UnderstandingNon-Disclosure AgreementPartnership Agreement - BusinessTermination')]</value>
      <webElementGuid>5426dca6-944d-40e6-8a7f-11425a9f1ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
