<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button - Yes JIK Payung</name>
   <tag></tag>
   <elementGuidId>8cc3cfb8-4b95-4ff3-bc06-cb6196c73c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7d9c981-1e97-49dc-b2d4-90893ab999a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>4cb5860d-514b-495c-8bd2-c5d76aab23bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bb51a6f6-e669-4353-b7c4-ebbd5a3c3f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jikpayung-existing</value>
      <webElementGuid>d50181b0-51c0-40ee-83de-056165d582c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>0185afb3-7eab-4d3a-b244-9baf53a9d838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes&quot;)</value>
      <webElementGuid>27dbd950-b7a0-4459-9d7a-68e5751824b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes']</value>
      <webElementGuid>a468f73e-4588-4ec1-8002-4b2e0dc72c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/div[8]/div/div/div/input</value>
      <webElementGuid>7d639b84-f7b0-43b7-8385-7951d8228563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>04891f3b-4d43-463f-8b03-2542151567ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yes' and @type = 'radio' and @name = 'jikpayung-existing']</value>
      <webElementGuid>a44cfd06-d3b9-4450-84f3-229f0e017bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
