<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button - Telkom as Partner</name>
   <tag></tag>
   <elementGuidId>03c291dd-f98a-45de-8f28-6080c92deaa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TelkomAsPartner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TelkomAsPartner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>768bd078-d9b3-48cb-a988-f1523a73b196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TelkomAsPartner</value>
      <webElementGuid>dd1acbaf-fb40-4784-9c27-eccbcd1f3226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bc46c91a-6ba0-4a71-833d-ec8907e29ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partnership-category</value>
      <webElementGuid>02d3c850-163d-42b5-bc5a-ca7d5cd2aacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TelkomAsPartner</value>
      <webElementGuid>98ca855a-5555-406c-a8ea-4806c96d8bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TelkomAsPartner&quot;)</value>
      <webElementGuid>e0e2ef9c-b5b7-4ec8-be46-faead57d3a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TelkomAsPartner']</value>
      <webElementGuid>275f5de9-ba8a-4a26-b8cf-5c9f4d5957f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/div[7]/div/div/div[2]/input</value>
      <webElementGuid>a4a6f99d-ddba-4e81-ba7c-22ae70f42c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8279ff0f-5911-4b51-87d4-fd1d0c36e8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TelkomAsPartner' and @type = 'radio' and @name = 'partnership-category']</value>
      <webElementGuid>a8ab1984-d29a-433e-819f-db9ce7952871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
