<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button - No JIK Payung</name>
   <tag></tag>
   <elementGuidId>c36ff6a4-a7f5-457a-bbc4-e4a376ee622a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>face51b2-1bef-4322-847c-a626bc9fdc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d512641c-b98b-4e50-abab-2225330e71fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1e56b448-7d87-4fb2-b47b-db87547a4a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jikpayung-existing</value>
      <webElementGuid>561ffaef-c8b4-4c6a-8f06-017ea293f333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8f05abaf-6772-421e-b7f5-7c8c04131967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no&quot;)</value>
      <webElementGuid>9685a01b-32c2-42c3-a019-684f0d08b514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no']</value>
      <webElementGuid>f2492ae9-7217-4c33-8b11-419371bfe4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/div[8]/div/div/div[2]/input</value>
      <webElementGuid>edde2077-d923-4b2b-8aa5-eafd3a413476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/input</value>
      <webElementGuid>4f6a7afc-4f65-484c-bec4-3ad334fdf408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no' and @type = 'radio' and @name = 'jikpayung-existing']</value>
      <webElementGuid>51674231-48ef-4250-b606-8da74a427690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
