<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button - Telkom Looking for Partner</name>
   <tag></tag>
   <elementGuidId>fc3c7950-37d9-4954-af2b-fc8c72b4fc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TelkomLookingForPartner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TelkomLookingForPartner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>977dad2d-00d7-4a08-83d7-95c49fd85356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TelkomLookingForPartner</value>
      <webElementGuid>715c7b1d-94fc-4274-9ad6-8b8857b439b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9e035533-aec0-464f-be7a-bcb7916b1367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partnership-category</value>
      <webElementGuid>a547de73-8374-4226-8a47-2facb8ee56c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TelkomLookingForPartner</value>
      <webElementGuid>7a69674e-3ccd-4149-a721-270e7c479835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TelkomLookingForPartner&quot;)</value>
      <webElementGuid>a3a7ec59-407a-47dc-9b57-cf312d03a600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TelkomLookingForPartner']</value>
      <webElementGuid>c0f7731f-1b66-47de-ad47-82deb57d5dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div[2]/div/div/div/div/div[7]/div/div/div/input</value>
      <webElementGuid>a15de0bc-e462-4f0c-a226-e17617be0b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>c1040eda-7274-4b91-984a-15ce1140078a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TelkomLookingForPartner' and @type = 'radio' and @name = 'partnership-category']</value>
      <webElementGuid>6c304f18-11db-4413-b5f3-2e396729b106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
